DROP TABLE IF EXISTS "categories";
CREATE TABLE "categories" ("id" INTEGER PRIMARY KEY  NOT NULL ,"name" VARCHAR,"deleted" INTEGER DEFAULT (0) );
INSERT INTO "categories" VALUES(10001,'Example Category',0);
DROP TABLE IF EXISTS "settings";
CREATE TABLE "settings" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR, "value" VARCHAR);
DROP TABLE IF EXISTS "stations";
CREATE TABLE "stations" ("id" INTEGER PRIMARY KEY  NOT NULL ,"name" VARCHAR,"category" INTEGER,"type" INTEGER,"url" VARCHAR,"deleted" INTEGER DEFAULT (0) );
INSERT INTO "stations" VALUES(10001,'Example Station',10001,10001,'http://stationip_or_url/1',0);
DROP TABLE IF EXISTS "type";
CREATE TABLE "type" ("id" INTEGER PRIMARY KEY  NOT NULL ,"name" VARCHAR,"deleted" INTEGER DEFAULT (0) );
INSERT INTO "type" VALUES(10001,'On/Off',0);
INSERT INTO "type" VALUES(10002,'Slider',0);
